sudo: false

language: node_js

node_js:
  - "6"
  - "4"
  - "0.12"
  - "0.10"

os:
  - linux
  - osx

matrix:
  fast_finish: true

script:
  - if [ $TRAVIS_NODE_VERSION == "6" ]; then
      npm run lint || exit 1;
    fi
  - npm run mocha

cache:
  directories:
    - node_modules

notifications:
    on_success: change
